version: '3.8'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: medods
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge